.github/workflows/test.yml, app/static/package-lock.json, app/static/package.json, app/static/src/app/components/WodinPanels.vue, app/static/src/app/components/basic/BasicApp.vue, app/static/src/app/components/run/RunModelPlot.vue, app/static/src/scss/style.scss, app/static/tests/e2e/basic.etest.ts, app/static/tests/unit/components/basic/basicApp.test.ts, app/static/tests/unit/components/run/runModelPlot.test.ts, app/static/tests/unit/components/wodinPanels.test.ts
Adds a component for the basic layout shown in the [mockups](https://docs.google.com/presentation/d/1uJqH_TR_v1F-hGkmkEKGduS7uGx2xrwbqVZ_DMZTA8w/edit) with left and right panels which can be collapsed/expanded with < and > buttons and 'View options'/'View charts' labels when collapsed.
The content to go in the panels is specified by the parent using 'left' and 'right' named slots. 
The component has been added the the 'Basic' app type only (i.e. the `BasicApp` component only), with placeholder basic app info being placed in the left panel (to be replaced in future with Code and Options tabs) and the proof of concept chart in the the right panel (to be replaced in future with real model visualisations). (The initial set of epics implement the Basic app type - Model Fit and Stochastic apps …
=> mrc-3148 Collapsible left and right panels

scripts/build-and-run.sh
Readlink is not supported in Mac so I replaced it with realpath which works on Ubuntu and Mac .
=> mrc-3186 replace realink with realpath

app/server/package-lock.json, app/server/package.json, app/server/src/server/server.ts
Adds out-of-the-box server logging with [morgan](https://www.npmjs.com/package/morgan) using the built-in 'short' format to get some basic logging in, with an idea of which sets of requests came from the same users. This format could potentially be replaced with full JSON logging as for HINT if required later.
=> mrc-3213 Added server logging

.gitignore, app/static/package-lock.json, app/static/package.json, app/static/playwright.config.ts, app/static/src/app/components/VerticalCollapse.vue, app/static/src/app/components/options/OptionsTab.vue, app/static/src/app/components/options/ParameterValues.vue, app/static/src/app/components/run/RunTab.vue, app/static/src/app/store/model/actions.ts, app/static/src/app/store/model/model.ts, app/static/src/app/store/model/mutations.ts, app/static/src/app/store/model/state.ts, app/static/src/app/types/responseTypes.ts, app/static/src/app/types/utilTypes.ts, app/static/src/app/userMessages.ts, app/static/tests/e2e/code.etest.ts, app/static/tests/e2e/index.etest.ts, app/static/tests/e2e/options.etest.ts, app/static/tests/e2e/panels.etest.ts, app/static/tests/e2e/tabs.etest.ts, app/static/tests/mocks.ts, app/static/tests/unit/components/basic/basicApp.test.ts, app/static/tests/unit/components/options/optionsTab.test.ts, app/static/tests/unit/components/options/parameterValues.test.ts, app/static/tests/unit/components/run/runTab.test.ts, app/static/tests/unit/components/verticalCollapse.test.ts, app/static/tests/unit/store/model/actions.test.ts, app/static/tests/unit/store/model/mutations.test.ts, scripts/run-dependencies.sh
Adds UI and store support for updating parameter values, implemented on the Options tab. When the user edits a parameter value, the model's `requiredAction` becomes 'Run' since the model needs to be re-run to reflect the new parameter value. 
When the model is recompiled, we do not retain the current set of parameter values, but overwrite them with defaults from the new code. 
Parameter metadata includes min, max, is_integer and rank values - on discussion with Rich it emerged that he would prefer not to enforce or indicate these in the UI, but allow the model to fail when run if parameter is outside bounds or wrong format. (There is an outstanding ticket to put in error handling.)
Includes a VerticalCollapse panel to allow ModelParameters to be collapsed by user - this will also be used …
=> mrc-3252 Basic Model Parameters UI

app/static/src/app/components/options/OptionsTab.vue, app/static/src/app/components/options/RunOptions.vue, app/static/src/app/components/run/RunModelPlot.vue, app/static/src/app/store/model/actions.ts, app/static/src/app/store/model/model.ts, app/static/src/app/store/model/mutations.ts, app/static/src/app/store/model/state.ts, app/static/src/app/userMessages.ts, app/static/tests/e2e/code.etest.ts, app/static/tests/e2e/options.etest.ts, app/static/tests/mocks.ts, app/static/tests/unit/components/options/optionsTab.test.ts, app/static/tests/unit/components/options/runOptions.test.ts, app/static/tests/unit/components/run/runModelPlot.test.ts, app/static/tests/unit/components/run/runTab.test.ts, app/static/tests/unit/store/model/actions.test.ts, app/static/tests/unit/store/model/mutations.test.ts
Adds End Time option, and uses it when running model. End Time defaults to 100 - a separate ticket will implement configuring default end time for applications. 
To test - run deps and app and browse to Day 1 app. Edit End time parameter - this should cause 're-run required' message to be displayed. When model is re-run, results on graph should be displayed up to the new end time.
=> mrc-3253 Add End Time to Options tab

app/static/package.json, app/static/src/app/components/options/ParameterValues.vue, app/static/src/app/store/model/actions.ts, app/static/src/app/store/model/model.ts, app/static/src/app/store/model/mutations.ts, app/static/src/app/store/model/state.ts, app/static/src/app/types/responseTypes.ts, app/static/tests/mocks.ts, app/static/tests/unit/components/options/optionsTab.test.ts, app/static/tests/unit/components/options/parameterValues.test.ts, app/static/tests/unit/store/model/actions.test.ts, app/static/tests/unit/store/model/mutations.test.ts, scripts/run-dependencies.sh
The model run interface is changing in the js runner returned by odin.api. This branch updates for these changes as follows:
- dopri and control are no longer required as parameters to the run method (dopri is now bundled up with the response, and we weren't using control anyway). 
- the runner returned from the endpoint is now an object rather than just a function. We call the method `wodinRun` on the object - and other methods will eventually be added around fit and sensitivity, 
- the parameters need to be passed as a Map rather than an ordinary object, so I've changed parameters to be Map in the state too.
=> mrc-3663 Use latest odin api

app/static/src/app/utils.ts, app/static/tests/unit/utils.test.ts
This PR allows missing values, either `""` or `NA` to be included within the upload, translating them to `NaN` in order to match the interface in odin-js (https://github.com/mrc-ide/odin-js/pull/12).
Some slight changes that follow from this:
* missing values are not allowed in the time column, so presence of a missing value there disallows the column from eligibility, even if the values are otherwise sorted
* blocks of missing data at the end of the file, which Excel can leave, are discarded
* because of the above, the "sufficient rows" check is done after the missing values are processed
=> Allow NA values in csv parse

README.md, scripts/build-frontend.sh
One of the reasons the WODIN build takes so long is because it builds js for each app type separately. Our build script (`./scripts/build-and-run.sh`) also rebuilds the backend too. However, typically in development, we make changes to the front end and want to quickly spin up a single app type to test changes.
This branch adds a helper build script which builds front end for a given app type only. It does not re-run the app as a running server will serve new js when page is re-loaded.
The script builds the front end for the requested app type then copies js etc to the server folder. For me, this reduced build time from ~2mins to ~1min. 
Run the script providing app type as an arg e.g. `./scripts/build-frontend.sh fit` or `./scripts/build-frontend.sh basic`
To test:
- spin up the app …
=> mrc-3442 Add build frontend script

app/static/jest.config.js, app/static/package-lock.json, app/static/package.json, app/static/src/app/components/options/NumericInput.vue, app/static/src/app/components/options/ParameterValues.vue, app/static/tests/e2e/options.etest.ts, app/static/tests/unit/components/options/numericInput.test.ts, app/static/tests/unit/components/options/parameterValues.test.ts
This branch implements a custom numeric input for parameter values, which:
- allows decimal inputs
- does not show a value spinner
- formats large numbers with comma thousands separators
The user can enter numerals, decimal point and commas, and this will be parsed as a number where possible. If the user input is not correctly formatted (e.g. comma separator in wrong place), this formatting will be corrected on blur of control (it's a poor UX to correct on every keystroke as user may still be inputting value). If value is NaN e.g. all commas or multiple decimal points, the displayed value will also be updated to last saved numeric on next blur. 
We also want to update the displayed value if a change of numeric value has originated external to the control, e.g. during Model Fit (not merged …
=> mrc-3296 Custom numeric input for parameter values

app/static/src/app/components/run/RunTab.vue, app/static/src/app/store/model/actions.ts, app/static/src/app/store/model/model.ts, app/static/src/app/store/model/mutations.ts, app/static/src/app/store/model/state.ts, app/static/tests/mocks.ts, app/static/tests/unit/components/run/runTab.test.ts, app/static/tests/unit/store/model/actions.test.ts, app/static/tests/unit/store/model/mutations.test.ts
This PR displays errors from model endpoints
To test:
* sabotage wodin api by stopping or restarting docker container
* `docker restart wodin.api`
* quickly type rubbish on code editor
* you should see an error displayed.
=> mrc-3290 Front end Error handling

app/server/package-lock.json, app/server/package.json, app/server/src/redis.ts, app/server/src/server/server.ts, app/server/src/types.ts, app/server/tests/redis.test.ts, config/wodin.config.json, scripts/run-dependencies.sh, scripts/run-dev-dependencies.sh
This is pretty basic, but hopefully an ok starting point. See https://github.com/mrc-ide/wodin-demo/pull/2 for deployment tweaks, which are fairly straightforward
I am stuck with the tests here, as my knowledge of how JS does async things is nonexistant. I tried adding a test file like:
```
import { redisConnection } from "../src/redis";
describe("redis", () => {
const mockConsoleLog = jest.fn();
const realConsoleLog = console.log;
const realArgs = process.argv;
beforeAll(() => {
console.log = mockConsoleLog;
});
afterAll(() => {
console.log = realConsoleLog;
process.argv = realArgs;
});
afterEach(() => {
jest.clearAllMocks();
});
it("can connect", () => {
const redis = redisConnection("redis://localhost:6379");
expect(mockConsoleLog).toBeCalledTimes(1); …
```
=> Add redis to app

app/static/src/app/components/fit/FitPlot.vue, app/static/src/app/components/fit/FitTab.vue, app/static/src/app/components/run/RunPlot.vue, app/static/src/app/components/run/RunTab.vue, app/static/src/app/plot.ts, app/static/tests/e2e/fit.etest.ts, app/static/tests/unit/components/fit/fitPlot.test.ts, app/static/tests/unit/components/fit/fitTab.test.ts, app/static/tests/unit/components/run/runPlot.test.ts, app/static/tests/unit/components/run/runTab.test.ts
This PR does a very literal decoupling of the plotting components, ahead of any refactoring.
I've copied the RunModelPlot component into run/RunPlot and fit/FitPlot and removed all the logic that switched on the fit prop, then reworked the tests so that everything remains.
There's some pretty obvious work to refactor the resizeable plotly plot. I can take a stab at that, but I don't know enough about Vue components to do a proper job really.
=> Decouple the two plots

app/static/src/app/store/sensitivity/actions.ts, app/static/tests/unit/store/sensitivity/actions.test.ts
Fixes a bug where, if a parameter value is changed, and sensitivity re-run, the plotted 'central' values on sensitivity plot showed the old parameter value trace. The central values use the odin solution in `model` module - the same one which is shown on the 'Run' tab. This module already has a flag indicating if run is required because the solution is of of date. So when we run sensitivity we now check that and dispatch `RunModel` action if run is required.
=> mrc-3514 Run sensitivity re-runs model if required

app/static/src/app/components/options/SensitivityOptions.vue, app/static/src/app/components/options/SensitivityPlotOptions.vue, app/static/src/app/components/sensitivity/SensitivityTab.vue, app/static/src/app/store/sensitivity/mutations.ts, app/static/src/app/store/sensitivity/sensitivity.ts, app/static/src/app/store/sensitivity/state.ts, app/static/tests/e2e/sensitivity.etest.ts, app/static/tests/mocks.ts, app/static/tests/unit/components/basic/basicApp.test.ts, app/static/tests/unit/components/fit/fitApp.test.ts, app/static/tests/unit/components/options/sensitivityOptions.test.ts, app/static/tests/unit/components/options/sensitivityPlotOptions.test.ts, app/static/tests/unit/components/sensitivity/sensitivityTab.test.ts, app/static/tests/unit/store/sensitivity/mutations.test.ts
This branch adds UI for selecting sensitivity plot type and related settings (min/max and time). Related settings are only shown for the relevant plot types. Settings are saved to the state, but are not yet used to plot sensitivity data for plot types other than Trace over time (a placeholder message is shown for other trace types). 
As per the shiny app, we let the user set any numeric time value, but will clip to 0 to model endTime range when we run the batch method to get the plot data
NB re the UI in the Options tab for this, Nick has suggested moving the Edit button for the Parameter variance up to the top right of that area to more closely link the bullet point value with the button. I think it might be useful to add headings to the two sections ('Parameter variance'/'Plot …
=> mrc-3433 Sensitivity plot options

app/static/playwright.config.ts, app/static/src/app/components/WodinOdePlot.vue, app/static/src/app/components/options/NumericInput.vue, app/static/src/app/components/options/RunOptions.vue, app/static/src/app/components/options/SensitivityPlotOptions.vue, app/static/src/app/components/sensitivity/SensitivitySummaryPlot.vue, app/static/src/app/components/sensitivity/SensitivityTab.vue, app/static/src/app/plot.ts, app/static/src/app/types/responseTypes.ts, app/static/src/scss/style.scss, app/static/tests/e2e/sensitivity.etest.ts, app/static/tests/mocks.ts, app/static/tests/unit/components/basic/basicApp.test.ts, app/static/tests/unit/components/fit/fitPlot.test.ts, app/static/tests/unit/components/options/numericInput.test.ts, app/static/tests/unit/components/options/runOptions.test.ts, app/static/tests/unit/components/options/sensitivityPlotOptions.test.ts, app/static/tests/unit/components/run/runPlot.test.ts, app/static/tests/unit/components/sensitivity/sensitivitySummaryPlot.test.ts, app/static/tests/unit/components/sensitivity/sensitivityTab.test.ts, app/static/tests/unit/components/sensitivity/sensitivityTracesPlot.test.ts, app/static/tests/unit/plot.test.ts
This branch implements 'Value at a single time' sensitivity plot. It includes a new plot component, `SensitivitySummaryPlot` which will call the appropriate methods on the sensitvity module's `batch` to get the sensitivity plot data. A future branch will implement the min/max plot types. 
The `SensitivitySummaryPlot` does share some code with `WodinOdePlot` around setting up the resize observer and calling `newPlot`. I didn't think it was worth making a further base component for them both to share, particularly since there are differences (the `WodinOdePlot` regenerates data on relayout (zoom) which we don't need to do here) so any base component would need to accommodate both of these requirements. I've pulled out common bits of config into the `plot` module.  
To test, run sensitivity, …
=> mrc-3435 Value at Time sensitivity plot

app/static/src/app/components/sensitivity/SensitivityTab.vue, app/static/src/app/store/sensitivity/actions.ts, app/static/src/app/store/sensitivity/mutations.ts, app/static/src/app/store/sensitivity/sensitivity.ts, app/static/src/app/store/sensitivity/state.ts, app/static/src/app/userMessages.ts, app/static/tests/mocks.ts, app/static/tests/unit/components/sensitivity/sensitivityTab.test.ts, app/static/tests/unit/store/sensitivity/actions.test.ts, app/static/tests/unit/store/sensitivity/mutations.test.ts
This branch catches any error which occurs when running sensitivity (`batchRun`) and displays it in `SensitivityTab`. The error is cleared on the next successful sensitivity run. 
You can force an error to be throwin in the day2 app, by editing Sensitivity Options to use VariationType: Range, and From: 0 with any positive value for To.
=> mrc-3518 Catch and display sensitivity run errors

app/server/src/controllers/sessionsController.ts, app/server/src/db/sessionStore.ts, app/server/src/routes/apps.ts, app/server/src/routes/odin.ts, app/server/src/server/server.ts, app/server/src/types.ts, app/server/tests/controllers/sessionsController.test.ts, app/server/tests/db/sessionStore.test.ts, app/server/tests/integration/session.test.ts, app/server/tests/integration/utils.ts, app/server/tests/routes/apps.test.ts, app/server/tests/routes/odin.test.ts, config/wodin.config.json
This branch adds an endpoint to store session data to redis. The url is `POST /:appName/sessions/:id` where `id` is a unique id for the sessions, which will be generated in the front end. Data is stored into redis at a key which includes the app name as well as the full course title (maybe course title isn't quite right though - that's intended to be human readable. It should be unique but we have no real way of enforcing that.) We also store the timestamp when session data was last updated.
=> mrc-3524 Endpoint to save session state

app/static/src/app/components/WodinOdePlot.vue, app/static/src/app/components/fit/FitPlot.vue, app/static/src/app/components/run/RunPlot.vue, app/static/src/app/components/sensitivity/SensitivityTracesPlot.vue, app/static/src/app/palette.ts, app/static/src/app/plot.ts, app/static/src/app/store/fitData/getters.ts, app/static/src/app/store/fitData/state.ts, app/static/tests/unit/components/fit/fitPlot.test.ts, app/static/tests/unit/components/run/runPlot.test.ts, app/static/tests/unit/components/sensitivity/sensitivityTracesPlot.test.ts, app/static/tests/unit/components/wodinOdePlot.test.ts, app/static/tests/unit/palette.test.ts, app/static/tests/unit/plot.test.ts, app/static/tests/unit/store/fitData/getters.test.ts
This PR adds data to the run plot if available. Things to note:
* this works in both the basic app (with no data) and the fit app, though some of that is just because of the way that truthiness cascades through (there's no checking to make sure that we should try (or not) and look for this in the basic app for example). I think that this is the same with other apps
* I've added the fit data to the solutions array to trigger a redraw. This works well on upload; after uploading data the plot is redrawn with the data points on it
* the colouring logic for the data is: unlinked data use our built-in data palette, but any linked data take on the colour of the series that they are linked to
* Changing the linked series does not trigger a redraw, rerunning the model does show the new colours …
=> Plot data on run plot, where available

app/static/src/app/localStorageManager.ts, app/static/src/app/store/basic/basic.ts, app/static/src/app/store/fit/fit.ts, app/static/src/app/store/stochastic/stochastic.ts, app/static/tests/unit/localStorageManager.test.ts, app/static/tests/unit/store/basic/basic.test.ts, app/static/tests/unit/store/fit/fit.test.ts, app/static/tests/unit/store/stochastic/stochastic.test.ts
This branch adds a `localStorageManager` and uses it to save the ids of new sessions into local storage. All historic session ids are kept as a serialised string array under a single key, `sessionIds`. 
To spy on this class in order to unit test its usage from the top level store modules, I seemed to need to do a dynamic import in the test, or the store modules would be loaded and the save triggered before the spy could be set up. 
To test, load the app, and check local storage in browser devtools (Application tab). You should see a new id added to the `sessionIds` key on each reload.
=> mrc-3526 Save Session Ids to local storage

.github/workflows/test.yml
It would appear that node v16.17.0 broke the backend test by setting `_dirname` differently to v16.16.0 (to /tmp..) and then config file was not accessible from this location - not sure if this is a bug or deliberate but pinning to the previous version seems to have fixed the issue for now!
=> Pin node version

app/static/src/app/components/options/RunOptions.vue, app/static/src/app/store/fitData/actions.ts, app/static/src/app/store/run/mutations.ts, app/static/tests/unit/components/options/runOptions.test.ts, app/static/tests/unit/store/fitData/actions.test.ts, app/static/tests/unit/store/run/mutations.test.ts
This PR makes the wodin interface match the existing shiny behaviour of taking the run end time from the data when possible. It's better than the shiny version though because you can run the model before uploading data.
Once data has been uploaded, end time becomes non-editable - I've changed it to a label but can do something else if there's another pattern. I made the label have "(from data)" added to it so that it's somewhat obvious where that number comes from
This PR also fixes mrc-3543 (don't rerun model if end time shrinks). Now that we have inputs it's pretty easy because we can just see if endTime is greater than the original endTime - if it's not then there's no need to rerun anything because we already have the solution to acceptable accuracy over that range.
=> In the fit app, take end time from data when available

app/static/src/app/components/fit/FitTab.vue, app/static/src/app/components/fit/support.ts, app/static/src/app/store/modelFit/actions.ts, app/static/src/app/store/modelFit/getters.ts, app/static/src/app/store/modelFit/state.ts, app/static/src/app/userMessages.ts, app/static/src/app/utils.ts, app/static/tests/unit/components/fit/fitApp.test.ts, app/static/tests/unit/components/fit/fitTab.test.ts, app/static/tests/unit/components/fit/support.test.ts, app/static/tests/unit/store/modelFit/actions.test.ts, app/static/tests/unit/store/modelFit/getters.test.ts, app/static/tests/unit/utils.test.ts
This PR breaks up our omnibus error message when we can't fit "Cannot fit model. Please provide valid data and code, link at least one variable and select parameters to vary." - watching science users with the app this was a bit of a stopper.
I've replaced the current getter with one that returns a Dict of booleans corresponding to different requirements. When constructing an error message with these there's also a bit of a graph there (no point telling the user to set a time variable if there is no data, or no point telling the user to select variable parameters if there is no model).
I've put the the message construction into the getter file which does not feel right but I wasn't sure where was better. It's fairly tied to the state in that part of the program.
For the rest of the app we …
=> mrc-3470: More actionable error messages if fit impossible

app/static/src/app/components/fit/FitTab.vue, app/static/src/app/components/fit/support.ts, app/static/src/app/components/options/ParameterValues.vue, app/static/src/app/store/fitData/actions.ts, app/static/src/app/store/model/actions.ts, app/static/src/app/store/modelFit/actions.ts, app/static/src/app/store/modelFit/getters.ts, app/static/src/app/store/modelFit/modelFit.ts, app/static/src/app/store/modelFit/mutations.ts, app/static/src/app/store/modelFit/state.ts, app/static/src/app/userMessages.ts, app/static/src/app/utils.ts, app/static/tests/e2e/fit.etest.ts, app/static/tests/mocks.ts, app/static/tests/unit/components/fit/fitTab.test.ts, app/static/tests/unit/components/fit/support.test.ts, app/static/tests/unit/components/options/parameterValues.test.ts, app/static/tests/unit/store/fitData/actions.test.ts, app/static/tests/unit/store/model/actions.test.ts, app/static/tests/unit/store/modelFit/actions.test.ts, app/static/tests/unit/store/modelFit/mutations.test.ts
This PR breaks apart one of the other omnibus error messages:
> Model code has been recompiled, or options or data have been updated. Fit Model for updated best fit.
with one that explains more precisely what has changed. This turned out to be a little more involved than the fit requirements one (#67) because it wasn't a case of looking at the inputs we have and saying "is this what I need" but keeping track of what has been invalidated. So I've updated the `fitUpdateRequired` member of state from being a boolean to being a Dict of reasons. When we update one of the bits of state that previously set this flag to `true` it now sets the reason. At that point the pattern looks very similar with a little helper to try and construct sensible error messages from the set of flags.
I have snuck …
=> More detailed reasons for fit update

app/static/src/app/store/modelFit/actions.ts, app/static/src/app/store/run/actions.ts, app/static/src/app/store/run/mutations.ts, app/static/tests/unit/store/model/actions.test.ts, app/static/tests/unit/store/modelFit/actions.test.ts, app/static/tests/unit/store/run/actions.test.ts, app/static/tests/unit/store/run/mutations.test.ts
~This will behave a bit better once #66 is merged as it has the effect of changing the solution end time weirdly, but it is actually independent.~
Currently we update the parameters but do not set the "needs run" flag. This PR updates the central solution directly from he model fit.
=> Update central solution when fit updates

README.md, scripts/run-version.sh
This adds a helper script for spinning up copies of the app without having to build it, using our docker images. It's a bit fragile in places, as all bash scripts are, but we can make it more robust as we use it.
For example, to try out the active serialisation PR (#70) you could run
```
./scripts/run-version.sh --app mrc-3525
```
which pulls down the new app code and brings it all up. Of course it uses the configuration in the current directory not the branch...
=> Add runner script

README.md, app/static/src/app/apiService.ts, app/static/src/app/serialise.ts, app/static/src/app/store/appState/actions.ts, app/static/src/app/store/appState/mutations.ts, app/static/src/app/store/appState/state.ts, app/static/src/app/store/basic/basic.ts, app/static/src/app/store/fit/fit.ts, app/static/src/app/store/fit/state.ts, app/static/src/app/store/plugins.ts, app/static/src/app/store/stochastic/stochastic.ts, app/static/src/app/types/responseTypes.ts, app/static/tests/mocks.ts, app/static/tests/unit/apiService.test.ts, app/static/tests/unit/serialiser.test.ts, app/static/tests/unit/store/appState/actions.test.ts, app/static/tests/unit/store/appState/mutations.test.ts, app/static/tests/unit/store/plugins.test.ts, config/apps/day1.config.json
This branch adds serialising session state and saving it to the session POST endpoint.
We follow a similar pattern to HINT, where each mutation (with some exceptions) cause a pending state save to be queued, and the save to take place two seconds later. This allows us to collect related groups of mutations into a single save request, to minimise traffic. This has some associated state e.g. interval id, and so we need to exclude mutation of these from triggering saves or we end up in an infinite loop!
State serialisation selectively includes the state properties required for later rehydration - e.g.  we do not include the odin solutions themselves. The serialisation takes quite a long-winded 'opt in' approach - each property of each module which we want to include in the serialisation is …
=> mrc-3525 Save session state

app/static/tests/unit/serialiser.test.ts
The serialisation PR (#70) interacts with the PR that introduced the fit update reasons (#71) but this is limited to type issues in the test only.
=> Fix build after merge issue

app/server/src/controllers/sessionsController.ts, app/server/src/db/sessionStore.ts, app/server/src/routes/apps.ts, app/server/tests/controllers/sessionsController.test.ts, app/server/tests/db/sessionStore.test.ts, app/server/tests/integration/session.test.ts, app/server/tests/integration/utils.ts, app/server/tests/routes/apps.test.ts
This just blatently duplicates the pattern from your previous PR (https://github.com/mrc-ide/wodin/pull/59)
The label ends up passed as a string, picks up the extra json quotes along the way, then gets stripped off (see the `JSON.parse` in sessionController.ts and the the bodyParser.text call in apps.ts - not sure if that's the best way
=> Add session label endpoint

app/server/src/controllers/sessionsController.ts, app/server/src/db/sessionStore.ts, app/server/src/routes/apps.ts, app/server/src/types.ts, app/server/tests/controllers/sessionsController.test.ts, app/server/tests/db/sessionStore.test.ts, app/server/tests/integration/session.test.ts, app/server/tests/integration/utils.ts, app/server/tests/routes/apps.test.ts
This branch adds the endpoint to get session metadata given a list of session ids, provided in a 'sessionIds' query string parameters where ids are comma-separated. The response data is an array of objects containing 'id' (session id), 'time' and 'label'.
This will be used to display metadata on the user's sessions on the Sessions page.
=> mrc-3535 Get sessions metadata

app/static/src/app/components/run/RunPlot.vue, app/static/src/app/components/sensitivity/SensitivityTracesPlot.vue, app/static/tests/unit/components/sensitivity/sensitivityTracesPlot.test.ts
We could probably do something additional for the other plot types, but it's not super easy, nor do I think it's that useful (and it's not on the existing shiny app either).
~Contains commits from #80, merge that first.~
=> Plot fit data on sensitivity traces plot

app/static/src/app/localStorageManager.ts, app/static/tests/unit/localStorageManager.test.ts
Don't append session ids, but prepend them, so that they come out naturally in reverse chronological order. Most recent will now always be first
=> Prepend session ids

app/static/src/app/components/fit/FitPlot.vue, app/static/src/app/components/run/RunPlot.vue, app/static/src/app/components/sensitivity/SensitivityTracesPlot.vue, app/static/src/app/types/responseTypes.ts, app/static/tests/unit/components/fit/fitPlot.test.ts, app/static/tests/unit/components/run/runPlot.test.ts, app/static/tests/unit/components/sensitivity/sensitivityTracesPlot.test.ts, scripts/run-dependencies.sh
Unpin branch in scripts/run-dependencies.sh before merging, after merging the odin PRs
Depends on https://github.com/mrc-ide/odin-js/pull/18, https://github.com/mrc-ide/odin/pull/271, https://github.com/mrc-ide/odin.api/pull/11
In https://github.com/mrc-ide/odin-js/pull/18 I've changed the solution so that we can both evaluate it over a grid of points (which we need for the plots) but also at some pre-specified set of points (which we would need to be able to evaluate the solution at exactly the same points in time as the data to fit to). This enables easy calculation of sum of squares without running or starting a fit.
=> Update to work with new odin-js, allowing better reuse of solution

app/server/package-lock.json, app/server/package.json, app/server/src/controllers/sessionsController.ts, app/server/src/db/sessionStore.ts, app/server/src/routes/apps.ts, app/server/tests/controllers/sessionsController.test.ts, app/server/tests/db/sessionStore.test.ts, app/server/tests/integration/session.test.ts, app/server/tests/routes/apps.test.ts
This uses an implementation of adjective-animal style ids that promises fairly "simple" versions of the ids, and seems to do ok at that.
The logic in id creation is a bit complicated if we want to avoid both collisions and pool exhaustion, but that seems worthwhile
Test with:
```
curl -X POST http://localhost:3000/apps/day1/sessions/c055e6ad675e274b93f1012f08bb5895/friendly
```
Hitting the same id twice will return the same friendly id, different ids will return different ids
=> Implement generation of friendly ids in session store

app/server/src/db/sessionStore.ts, app/server/tests/db/sessionStore.test.ts, app/server/tests/integration/session.test.ts
This PR reverts the change added within #89 that allowed multiple hyphens and instead sanitises names so that we:
* always return lower case everything
* never have more than one hyphen
I've looked though zoo-ids lists and we only get uppercase letters for "French" and "Spanish", and only get multiple hyphens for adjectives
=> Clean up ids

app/static/src/app/components/sensitivity/SensitivityTab.vue, app/static/src/app/store/modelFit/actions.ts, app/static/tests/e2e/fit.etest.ts, app/static/tests/unit/store/modelFit/actions.test.ts
See ticket for the issue and instructions to replicate. This was a regression that probably used to work ok because we changed how we kept track of sensitivity being in/out of date and because we changed how the fit sets the parameters/solution back into the state. The fix is simple enough though
As this has definitely broken before I've added a simple e2e test
=> Fix logic in sensitivity update

app/static/src/app/components/WodinOdePlot.vue, app/static/src/app/components/WodinSession.vue, app/static/src/app/components/fit/FitPlot.vue, app/static/src/app/components/fit/FitTab.vue, app/static/src/app/plot.ts, app/static/src/app/serialise.ts, app/static/src/app/store/appState/actions.ts, app/static/src/app/store/model/actions.ts, app/static/src/app/store/run/actions.ts, app/static/src/app/store/sensitivity/actions.ts, app/static/src/app/store/sessions/actions.ts, app/static/src/app/types/serialisationTypes.ts, app/static/src/app/types/wrapperTypes.ts, app/static/tests/e2e/fit.etest.ts, app/static/tests/e2e/index.etest.ts, app/static/tests/e2e/sessions.etest.ts, app/static/tests/e2e/utils.ts, app/static/tests/unit/components/fit/fitPlot.test.ts, app/static/tests/unit/components/wodinOdePlot.test.ts, app/static/tests/unit/components/wodinSession.test.ts, app/static/tests/unit/serialiser.test.ts, app/static/tests/unit/store/appState/actions.test.ts, app/static/tests/unit/store/model/actions.test.ts, app/static/tests/unit/store/run/actions.test.ts, app/static/tests/unit/store/sensitivity/actions.test.ts, app/static/tests/unit/store/sessions/actions.test.ts
This branch restores all session data and plots when load session from Sessions page. It re-runs model (Run tab) and sensitivity if these had previously been run. ModelFit is not re-run (we don't want to re-fit and change parameter values), but model fit is plotted from the model run solution if rehydration is detected. 
This uses the `result.inputs` values in the serialised state to rehydrate model runs from the actual inputs which were previously used, not the current values in the state (which may have changed without re-running). If compile was required when the session was last saved, the model is assumed to be stale, and is not re-run. 
To test:
- open day 1 or day 2 app and make changes e.g. code changes, upload data, fit model 
- reload the app to create a new current session
- …
=> mrc-3584 Full session rehydrate

app/static/src/app/components/ErrorsAlert.vue, app/static/src/app/components/WodinApp.vue, app/static/src/app/components/sessions/SessionsPage.vue, app/static/src/scss/style.scss, app/static/tests/unit/components/errorsAlert.test.ts, app/static/tests/unit/components/sessions/sessionsPage.test.ts
This branch improves the placement and styling of the errors alert which displays generic unexpected errors, typically those which occur when there is a problem with communicating with the back end (so not expected errors caused by user interaction e.g. compilation error, which are shown in the appropriate part of the UI). 
Before:
After:
Changes:
- move the alert to the top of the page so you can actually see it!
- add the alert to the Sessions page so comms errors are visible there too
- avoid x button wrapping onto next line
- improve look by including correct button class, making text colour consistent with the other error text, and using white background rather than bootstrap default pink, which clashes nastily with the brand teal
As noted on the ticket, I believe I've seen instances …
=> mrc-3347 Improve Errors Alert placement and style

app/server/src/controllers/appsController.ts, app/server/tests/controllers/appsController.test.ts, app/static/tests/e2e/index.etest.ts
The views were already trying to set page title from the `title` prop passed to then, but that had got missed out somewhere along the way. This reinstates the `title` prop and sets it to `[course title] - [app title]`
=> mrc-3573 Set Title in app pages

app/static/package-lock.json, app/static/package.json, app/static/src/app/components/DownloadOutput.vue, app/static/src/app/components/run/RunTab.vue, app/static/src/app/store/run/actions.ts, app/static/src/app/store/run/mutations.ts, app/static/src/app/store/run/run.ts, app/static/src/app/store/run/state.ts, app/static/src/app/userMessages.ts, app/static/src/app/wodinExcelDownload.ts, app/static/tests/e2e/download.etest.ts, app/static/tests/mocks.ts, app/static/tests/unit/components/downloadOutput.test.ts, app/static/tests/unit/components/run/runTab.test.ts, app/static/tests/unit/serialiser.test.ts, app/static/tests/unit/store/run/actions.test.ts, app/static/tests/unit/store/run/mutations.test.ts, app/static/tests/unit/wodinExcelDowload.test.ts
This branch adds download of model outputs from Run tab as an Excel file (.xlsx). Download from Fit tab will be implemented in a separate ticket. 
The contents of the file are:
- `Modelled` sheet, containing modelled points for all variables, along with a 't' column for times. This contains as many time points as the user selects in the download dialog, interpolated between 0 and the model end time. 
- `Modelled with Data` sheet, included only for Fit apps which have data uploaded. This contains all the time points from the data file, along with all data values, and also all model variable values for those times. 
- `Parameters` sheet, containing name and value for all parameters. 
Key changes:
- Download button added to Run tab. The button is disabled when update is required, or when the …
=> mrc-3656 Download model output

app/static/src/app/stochastic.ts, app/static/tests/e2e/download.etest.ts, app/static/tests/e2e/tabs.etest.ts
Main build is broken because of failing browser tests - I think these are tests which perhaps weren't running reliably before Lekan fixed up the browser tests in a recently merged in branch.
Two e2e tests hadn't been updated for behaviour changes, and there was one bug, which meant stochastic app wasn't being loaded (failing in router because passing wrong value for baseUrl parameter).
=> mrc-3717 Fix stochastic app bug, and update e2e tests

app/static/src/app/components/header/VersionMenu.vue
Fixes another failing e2e following the Playwright config improvement which now means all the tests actually get run reliably!
This one was failing because a class which the e2e test was checking for had been removed from the versions menu item.
=> mrc-3718 fix e2e tabs test

app/static/src/app/components/run/RunTab.vue, app/static/src/app/plot.ts, app/static/src/app/serialise.ts, app/static/src/app/store/run/actions.ts, app/static/src/app/types/responseTypes.ts, app/static/src/app/types/wrapperTypes.ts, app/static/src/app/wodinExcelDownload.ts, app/static/tests/unit/components/fit/fitPlot.test.ts, app/static/tests/unit/components/run/runPlot.test.ts, app/static/tests/unit/components/run/runTab.test.ts, app/static/tests/unit/components/sensitivity/sensitivitySummaryPlot.test.ts, app/static/tests/unit/components/sensitivity/sensitivityTracesPlot.test.ts, app/static/tests/unit/plot.test.ts, app/static/tests/unit/serialiser.test.ts, app/static/tests/unit/store/run/actions.test.ts, app/static/tests/unit/wodinExcelDowload.test.ts, scripts/run-dependencies.sh
Uses https://github.com/mrc-ide/odin.api/pull/16, https://github.com/mrc-ide/odin/pull/278 - the underlying js code changes in https://github.com/mrc-ide/odin-js/pull/21, https://github.com/mrc-ide/dust-js/pull/11 are merged, some coordination required to merge.
Unpin branch in dependencies script before merge
Does not yet include changes to work with https://github.com/mrc-ide/wodin/pull/116
=> Refactor to use new return types

app/server/src/apiService.ts, app/server/src/controllers/appsController.ts, app/server/src/controllers/odinController.ts, app/server/src/controllers/sessionsController.ts, app/server/src/errors/asyncControllerHandler.ts, app/server/tests/controllers/appsController.test.ts, app/server/tests/controllers/sessionsController.test.ts, app/server/tests/errors/asyncControllerHandler.test.ts, app/static/tests/e2e/index.etest.ts
This fixes entire application crashing when a non-existent app was requested, e.g. http://localhost:3000/apps/day4
Async handlers do not automatically use the express application's error handler when they throw, but need to explicitly call `next`.  (as descibed [here](https://reflectoring.io/express-error-handling/).)
This branch adds a wrapper method, `asyncControllerHandler` which does this - any async controller methods should use this wrapper *except* if they just use `apiService` to call out to an external service (as `odinController` does) since `apiService` already handles errors in this way.  The wrapper has been applied to `appsController` (which was causing this bug) and `sessionsController`. 
To test, browse to http://localhost:3000/apps/day4 - should see a Page Not Found html …
=> mrc-3752 Stop application crash when error during async controller method

app/static/src/app/plot.ts, app/static/tests/unit/components/fit/fitPlot.test.ts, app/static/tests/unit/components/run/runPlot.test.ts, app/static/tests/unit/components/sensitivity/sensitivitySummaryPlot.test.ts, app/static/tests/unit/components/sensitivity/sensitivityTracesPlot.test.ts, app/static/tests/unit/plot.test.ts
Fixes issue noticed by Romain, hover labels are truncated.
For a test case, try running this code, with a long parameter name:
```
deriv(S) <-  - beta * S * I / N
deriv(I) <- beta * S * I / N - sigma_long_name * I
deriv(R) <- sigma_long_name * I
initial(S) <- N - I0
initial(I) <- I0
initial(R) <- 0
N <- user(1e6)
I0 <- user(1)
beta <- user(4)
sigma_long_name <- user(2)
```
then in sensitivity set that to be the parameter that varies. You should see labels like `(<x>, <y>) S (sigma_l....` (e.g., in the version deployed at https://wodin-dev.dide.ic.ac.uk/apps/day1/ ). With this fix we get the long label `(<x> <y>) S (sigma_long_name=10)`
=> Don't truncate labels

app/static/src/app/components/sensitivity/SensitivitySummaryPlot.vue, app/static/src/scss/style.scss
The bug with the Download button disappearing/floating upwards was caused, I think, by plotly resetting the height of its div element when redrawing on zoom, and the DOM being somehow unable to catch up. This was fixed by setting that element to have a fixed height of 450px (perhaps not ideal, but that's what's we've been getting anyway as plotly's default) - this is set in a class which is applied to both `WodinPlot` and `SensitivitySummaryPlot`. 
However, this caused another issue: because the plot div now has fixed full height, that meant that the placeholder (shown when there is no plot data), placed after the plot div in the DOM, would be shown with a big plot-sized gap above it. Various attempts to hide the plot div, or temporarily set its height to 0 caused the same sorts of …
=> mrc-3749 Fix wandering Download button

app/static/src/app/components/WodinPlot.vue, app/static/src/app/components/options/GraphSettings.vue, app/static/src/app/components/options/OptionsTab.vue, app/static/src/app/components/sensitivity/SensitivitySummaryPlot.vue, app/static/src/app/serialise.ts, app/static/src/app/store/appState/state.ts, app/static/src/app/store/basic/basic.ts, app/static/src/app/store/fit/fit.ts, app/static/src/app/store/graphSettings/graphSettings.ts, app/static/src/app/store/graphSettings/mutations.ts, app/static/src/app/store/graphSettings/state.ts, app/static/src/app/store/stochastic/stochastic.ts, app/static/src/app/types/serialisationTypes.ts, app/static/tests/e2e/options.etest.ts, app/static/tests/mocks.ts, app/static/tests/unit/components/basic/basicApp.test.ts, app/static/tests/unit/components/fit/fitApp.test.ts, app/static/tests/unit/components/fit/fitTab.test.ts, app/static/tests/unit/components/options/graphSettings.test.ts, app/static/tests/unit/components/options/optionsTab.test.ts, app/static/tests/unit/components/sensitivity/sensitivitySummaryPlot.test.ts, app/static/tests/unit/components/stochastic/stochasticApp.test.ts, app/static/tests/unit/components/wodinPlot.test.ts, app/static/tests/unit/serialiser.test.ts, app/static/tests/unit/store/graphSettings/mutations.test.ts
This branch adds 'Graph Settings' as a new section on the Options tab. Currently the only graph setting is the option to plot values on the y axis with log scale. Setting this value will use log scale for all plots on all tabs, except for Sensitivity summary plots, when the plot type is 'Time at value's min/max' (since it does not make sense to plot Tme on log scale). 
This setting is currently false by default for all apps, but we may make default value configurable in future. 
There are likely to be further graph settings in the future, so the `graphSettings' module will be less empty than this initial version.
=> mrc-3425 Option for log scale y axis on plots

README.md, app/server/README.md, app/server/package-lock.json, app/server/package.json, app/server/src/configReader.ts, app/server/src/server/args.ts, app/server/src/server/server.ts, app/server/tests/server/args.test.ts, docker/browser_tests, docker/wodin
This PR reworks the command line processing to allow overriding of elements in config. I've swapped out `yargs` for `docopt` because we use that elsewhere and it's generally ok. I've also reworked `args.ts` to be side-effect free and fall back on `process.argv` using the same pattern we do in R packages.
The only usage difference is that `--config=path` becomes the positional argument `path`, with this change made as it's required and this is more conventional. I can roll that back easily enough if needed.
Once this is merged there may be some small tweaks required to deployment scripts, but anything using docker will work out the box
=> Overrideable configuration

app/server/src/server/server.ts, app/server/src/types.ts, config/wodin.config.json
We had redisURL and baseUrl floating around, all very confusing. 
We'll have to update some configurations after merge, but deploy is broken anyway (I know why).
This is seen working in the wodin-proxy PR: https://github.com/mrc-ide/wodin-proxy/pull/1
=> Fix url used to control redis server

app/static/src/app/components/code/CodeTab.vue, app/static/src/app/store/appState/actions.ts, app/static/src/app/store/appState/mutations.ts, app/static/src/app/store/appState/state.ts, app/static/src/app/store/basic/basic.ts, app/static/src/app/store/fit/fit.ts, app/static/src/app/store/sessions/actions.ts, app/static/src/app/store/stochastic/stochastic.ts, app/static/tests/mocks.ts, app/static/tests/unit/components/basic/basicApp.test.ts, app/static/tests/unit/components/code/codeTab.test.ts, app/static/tests/unit/serialiser.test.ts, app/static/tests/unit/store/appState/actions.test.ts, app/static/tests/unit/store/appState/mutations.test.ts, app/static/tests/unit/store/sessions/actions.test.ts
I'm prettty sure the bug with code not always showing in the editor was happening because the editor component  was sometimes loading before default code had been fetched with the app config, so the editor was getting initialised with empty code. Could have put something in to allow the editor to accept code changes from the state after being loaded but that would have needed to check difference from current value (to avoid infinite update loop) which could have got sticky interacting with the pending changes etc. So instead I've just introduced a 'configured' flag to the state which gets set when config and defaults are loaded.  Code editor is not displayed until app is configured. 
I haven't seen the bug recur after putting in this change, but of course, it's intermittent..
=> mrc-3906 Only show code tab content when app is configured

app/static/src/app/components/options/ParameterSetView.vue, app/static/src/app/components/run/RunPlot.vue, app/static/src/app/components/sensitivity/SensitivityTracesPlot.vue, app/static/src/app/directives/tooltip.ts, app/static/src/app/store/run/actions.ts, app/static/src/app/store/run/getters.ts, app/static/src/app/store/run/mutations.ts, app/static/src/app/store/run/state.ts, app/static/src/scss/style.scss, app/static/tests/e2e/options.etest.ts, app/static/tests/unit/components/options/parameterSetView.test.ts, app/static/tests/unit/components/options/parameterSets.test.ts, app/static/tests/unit/components/run/runPlot.test.ts, app/static/tests/unit/components/sensitivity/sensitivityTracesPlot.test.ts, app/static/tests/unit/serialiser.test.ts, app/static/tests/unit/store/run/actions.test.ts, app/static/tests/unit/store/run/getters.test.ts, app/static/tests/unit/store/run/mutations.test.ts, app/static/tests/unit/store/sensitivity/getters.test.ts
This branch allows the user to hide/show traces for a parameter set on Run and Sensitivity graphs by clicking on the eye icon in the parameter set in the Options tab. When a Parameter Set is hidden, its background is greyed out. 
There are two VueFeather icon components, one for Hide and the other for Show, rather than just one whose icon, tooltip etc gets updated when the `hidden` value changes - this is because I had problems getting the tooltip to update via the directive. Updating content in the existing `Tooltip` threw an error in Bootstrap, and creating a new `Tooltip` object on value update was flaky (new tooltip was not always immediately shown). I'll made a ticket to look into this properly as it would be nice to have an updating tooltip directive, but for now using two icons …
=> mrc-3256 Hide/show parameter set traces

docker/Dockerfile, docker/update-site, docker/update-sites
I know I said we might do this with node on the server, but this is probably enough for now as a little bash script.
The only really hairy bit is trying to resolve the reference argument nicely. If it's a branch name it's important that we match the remote one, not the locally checked out sources (so main is really origin/main). However, if the user has provided a hash or a tag then we need to match the tag directly. I don't think there's as way of saying "resolve this reference like the remote would" because that would simplify things. There may be an entirely different way of doing this aside from rev-parse but who knows.
Once we have the reference, we do a hard reset on the repo, which just says "get here, I don't care how". To keep this all tidy, I've deleted the default branch from …
=> Add bash script to update sources

app/static/src/app/components/options/ParameterSetView.vue, app/static/src/app/components/options/ParameterSets.vue, app/static/src/app/plot.ts, app/static/src/app/store/run/getters.ts, app/static/tests/e2e/options.etest.ts, app/static/tests/unit/components/options/parameterSetView.test.ts, app/static/tests/unit/components/options/parameterSets.test.ts, app/static/tests/unit/plot.test.ts
This branch updates the parameter set view to add an indication of the set's  line style in the graphs. This is shown next to parameter set name. 
Css is used to approximate the plotly line style. There are five line styles:
- dot
- dash
- longdash
- dashdot
- longdashdot
Most of these are implemented using css linear gradient, except for dot, which uses border-style. Perhaps this should use linear gradients too, just to be consistent?
Could have also used border-style for dash - however this does not give any control over the length of the dashes (which need to be shorter than longdash), and also I found that the line began with a shorter dash, which was visually confusing, and could be misinterpreted as dashdot. 
Css spec also includes a dashdot border style, but this is not well …
=> mrc-3255 Show trace line style in parameter set view

app/static/src/app/components/sensitivity/SensitivitySummaryPlot.vue, app/static/src/app/components/sensitivity/SensitivityTracesPlot.vue, app/static/src/app/plot.ts, app/static/src/app/types/responseTypes.ts, app/static/tests/unit/components/sensitivity/sensitivitySummaryPlot.test.ts, app/static/tests/unit/serialiser.test.ts
This branch adds traces for parameter set results to the sensitivity summary plot. This can lead to some odd looking charts if the parameter being varied by sensitivity also has different values across the parameter sets. We may modify valid combinations of values in future tickets. 
There is no e2e in this branch as I realised that plot summary data is not rendered in the sensitivity summary plot. There's a separate ticket to add this, update summary plot e2e tests, and add parameter set test: https://mrc-ide.myjetbrains.com/youtrack/issue/mrc-3935
=> mrc-3894 Show parameter set traces on Sensitivity Summary plot

app/server/src/controllers/configController.ts, app/server/src/types.ts, app/server/tests/controllers/configController.test.ts, app/static/src/app/store/appState/actions.ts, app/static/src/app/types/responseTypes.ts, app/static/tests/mocks.ts, app/static/tests/unit/components/code/codeEditor.test.ts
* made return types more extendable, and filled in bits that were missing in the server response types but used in the static app (this worked previously because we have no validation and because we just pass along the json content)
* harmonised the return types between the server and the client
* remove `baseUrl` from the app config response; this seems harmless to me so far?
I  have added in the as-yet-unused parameters for the stochastic control PR that triggered all of this (#135, mrc-3710) as this makes it all a bit clearer I think
=> Fill in defaults when returning app config

app/static/src/app/components/WodinPlot.vue, app/static/src/app/components/WodinPlotDataSummary.vue, app/static/src/app/components/sensitivity/SensitivitySummaryPlot.vue, app/static/tests/e2e/sensitivity.etest.ts, app/static/tests/e2e/sessions.etest.ts, app/static/tests/e2e/utils.ts, app/static/tests/unit/components/sensitivity/sensitivitySummaryPlot.test.ts, app/static/tests/unit/components/wodinPlot.test.ts, app/static/tests/unit/components/wodinPlotDataSummary.test.ts
This branch adds hidden data summary info to the `SensitivitySummaryPlot` to match `WodinPlot`. The relevant parts of template have been pulled out of `WodinPlot` and made into a separate component which is now used by both plots. 
I've also added a missing e2e test, for parameter set traces rendered in the sensitivity summary plot, using the new data summary. 
Updated session e2e test which had become flaky - don't assume labels will update immediately.
=> mrc-3935 Include hidden data summary in sensitivity summary plot

app/static/src/app/components/options/ParameterSetView.vue, app/static/src/app/store/run/actions.ts, app/static/src/app/store/run/mutations.ts, app/static/src/app/store/sensitivity/mutations.ts, app/static/tests/e2e/options.etest.ts, app/static/tests/e2e/sensitivity.etest.ts, app/static/tests/e2e/utils.ts, app/static/tests/unit/components/options/parameterSetView.test.ts, app/static/tests/unit/store/run/actions.test.ts, app/static/tests/unit/store/run/mutations.test.ts, app/static/tests/unit/store/sensitivity/mutations.test.ts, package-lock.json
This PR will add a "shuffle" vue feather icon to swap current parameter values with the parameter set values. This PR will add the following:
- VueFeather: "shuffle" icon
- RunAction: SwapParameterSet - commits SwapParameterSet mutation and ParameterSetSwapped sensitivity mutation if rerun is not required
- RunMutation: SwapParameterSet - swaps parameter values and results (so both values and graphs update)
- SensitivityMutation: ParameterSetSwapped - swaps sensitivity results (sensitivity graphs)
- Testing on all of the above
Note: the swap uses JavaScript de-structuring to swap the values, sensitivity swap can lag a tiny bit
=> Will add another icon button on the parameter set to swap parameter set with current parameter values

app/static/src/app/components/help/DraggableDialog.vue, app/static/tests/unit/components/help/draggableDialog.test.ts
Allows user to resize the generic help dialog down to a minimum size. Constrains title to a single line - it gets messy when it wraps at small sizes!
I've made the resize work from a single handle in the lower right rather than being able to pull out from the sides - mostly just for simplicity, Thoughts on the handle design? Had to cook something up myself for this as there wasn't a standard feather icon. It's based on the resize handle on github.com editor panes!
=> mrc-3960 Resize generic help dialog

app/static/src/app/components/code/CodeEditor.vue, app/static/src/app/components/code/CodeTab.vue, app/static/src/app/serialise.ts, app/static/src/app/store/code/code.ts, app/static/src/app/store/code/mutations.ts, app/static/src/app/store/code/state.ts, app/static/src/app/userMessages.ts, app/static/tests/e2e/code.etest.ts, app/static/tests/mocks.ts, app/static/tests/unit/components/code/codeTab.test.ts, app/static/tests/unit/serialiser.test.ts, app/static/tests/unit/store/code/mutations.test.ts
- Code validation from the back-end takes time so we want a loading state for it
- Add loading property to `CodeState`
- Toggle loading state when code changes in the editor or when code is validated
- Loading spinner for code validation
- Changed valid and invalid icon for consistent styling
- Type something into the code editor, it should show loading for a bit
1. Run the app according to the README
=> mrc-4305 Add loading to code status

app/server/src/configReader.ts, app/server/tests/configReader.test.ts, app/server/tests/examples/bom.json
A bit of a fight here. There is a package that does this (https://www.npmjs.com/package/strip-bom) but pulling that in requires changing the tsconfig to allow module interop and that breaks some mocks.  The code is very simple though so I pulled it in. See https://github.com/nodejs/node-v0.x-archive/issues/1918 for an issue where others have struggled with the underlying issue.
Deployed at https://wodin-dev.dide.ic.ac.uk/infectiousdiseasemodels-2023/apps/ebola/ where it works ok
=> Allow bom markers

app/static/src/app/components/code/CodeEditor.vue, app/static/src/app/components/help/GenericHelp.vue, config/apps/day1_nocode.config.json, config/index.html
The help icon was actually being rendered to the page but was hidden behind the code editor in the case where the reset button was not being rendered, because it is styled to float. Setting clear style on the subsequent element fixes this.
Also added a variant of the Day1 app with no default code to the default config so this case is easy to test locally.
=> gh-169 Style fix to display help icon if reset code button is not rendered

app/static/package-lock.json, app/static/package.json, app/static/src/app/components/options/AdvancedSettings.vue, app/static/src/app/components/options/TagInput.vue, app/static/src/app/serialise.ts, app/static/src/app/store/modelFit/actions.ts, app/static/src/app/store/run/actions.ts, app/static/src/app/store/run/mutations.ts, app/static/src/app/store/run/run.ts, app/static/src/app/store/run/state.ts, app/static/src/app/store/sensitivity/actions.ts, app/static/src/app/types/payloadTypes.ts, app/static/src/app/types/responseTypes.ts, app/static/src/app/types/serialisationTypes.ts, app/static/src/app/utils.ts, app/static/tests/e2e/code.etest.ts, app/static/tests/mocks.ts, app/static/tests/unit/components/options/advancedSettings.test.ts, app/static/tests/unit/components/options/tagInput.test.ts, app/static/tests/unit/serialiser.test.ts, app/static/tests/unit/store/modelFit/actions.test.ts, app/static/tests/unit/store/run/actions.test.ts, app/static/tests/unit/store/run/mutations.test.ts, app/static/tests/unit/store/sensitivity/actions.test.ts, app/static/tests/unit/utils.test.ts, app/static/vue-shims.d.ts
- We want to allow users to enter an array of critical times in the advanced settings to allow them to cope with discontinuous derivatives
- Changed advanced settings config to type instead of standard form boolean since we had 3 different types of input now
- TagInput component that parses and cleans tag inputs
- Can input numbers into the tag input and render a tag when you press Space, Enter or ","
- Can input parameter names into the tag input and it will format according to the values of the parameter
- Can change parameters and the tag should update
- Will not accept a non-parameter name string
- Will not accept repeats including parameter names however will accept "sigma" and "2" even if the value of sigma is 2
- Removing a parameter value in the code and compiling should remove it …
=> Mrc 4481 Allow an array of values in the tcrit advanced option

app/static/src/app/components/sensitivity/SensitivitySummaryPlot.vue, app/static/tests/e2e/code.etest.ts, app/static/tests/unit/components/sensitivity/sensitivitySummaryPlot.test.ts
Fixes the bug where legend visibility could not be toggled in the Sensitivity Summary Plot, by breaking the reactivity loop where every update caused an unnecessary mutation to set loading to false. 
Also contains unrelated fix for test - new code error message expected from latest version of odin.
=> mrc-4520 Prevent SetLoading reactivity loop in summary plot

app/static/src/app/components/WodinPanels.vue, app/static/tests/e2e/panels.etest.ts, app/static/tests/unit/components/basic/basicApp.test.ts, app/static/tests/unit/components/fit/fitApp.test.ts, app/static/tests/unit/components/stochastic/stochasticApp.test.ts, app/static/tests/unit/components/wodinApp.test.ts, app/static/tests/unit/components/wodinPanels.test.ts
- Users would like finer control over the size of the wodin panel, especially those with smaller screens since the space is limited
- Replaced two arrows with one vue feather that mimics the resize icon (could not actually find this icon so have rotated a maximise icon)
- Clicking and dragging this icon will resize the panel
- Hovering over the icon should change cursor to resize cursor
- Clicking and dragging should resize the panel
- Dragging within `windowWidth / 8` on the left side of the screen will snap the panel to the left
- Dragging within `windowWidth / 4` on the right side of the screen will snap panel to the right
- Dragging on any collapsed view should not change anything until your cursor gets beyond the collapse threshold for either side
- Clicking "View Options" or …
=> Mrc 3701 Resizable Panel

app/static/src/app/components/options/EditParamSettings.vue, app/static/src/app/components/options/SensitivityOptions.vue, app/static/src/app/components/options/TagInput.vue, app/static/src/app/store/sensitivity/sensitivity.ts, app/static/src/app/store/sensitivity/state.ts, app/static/src/app/utils.ts, app/static/tests/e2e/sensitivity.etest.ts, app/static/tests/mocks.ts, app/static/tests/unit/components/options/editParamSettings.test.ts, app/static/tests/unit/components/options/sensitivityOptions.test.ts, app/static/tests/unit/components/options/tagInput.test.ts, app/static/tests/unit/serialiser.test.ts, app/static/tests/unit/store/sensitivity/getters.test.ts, app/static/tests/unit/utils.test.ts
This branch adds a new sensitivity parameter settings variation type, "User", to the existing types ("Percentage" and "Range"). This allows the user to manually specify the parameter values to use in the sensitivity run.
On reflection, "User" maybe isn't a great term to surface to the, err, user. What would be better? "Values"? "Specific"?
This isn't doing any validation that the parameter's central value is between the lowest and highest values specified - should it?
Key changes:
- `userValues` number array added to the settings type to hold these values
- `EditParamSettings` dialog updated to support editing these values using the `TagInput`, plus read-only display in the options tab. The green alert showing generated values is not displayed for user values (as would be showing the same …
=> mrc-4522 Allow user-specified parameter values in Sensitivity

app/server/src/controllers/appsController.ts, app/server/tests/controllers/appsController.test.ts, app/static/tests/e2e/tabs.etest.ts, config/wodin.config.json
Switches off i18n by default so language switcher will not be displayed if `enablei18n` is not included in `wodin.config.json`.
Also switches off i18n in the dev config.
=> mrc-4521 Default to i18n not enabled

app/static/src/app/components/mixins/baseSensitivity.ts, app/static/src/app/components/multiSensitivity/MultiSensitivityTab.vue, app/static/src/app/components/sensitivity/SensitivitySummaryDownload.vue, app/static/src/app/components/sensitivity/SensitivityTab.vue, app/static/src/app/excel/wodinExcelDownload.ts, app/static/src/app/excel/wodinSensitivitySummaryDownload.ts, app/static/src/app/store/sensitivity/actions.ts, app/static/src/app/store/sensitivity/mutations.ts, app/static/tests/e2e/download.etest.ts, app/static/tests/unit/components/mixins/baseSensitivity.test.ts, app/static/tests/unit/components/multiSensitivity/multiSensitivityTab.test.ts, app/static/tests/unit/components/sensitivity/sensitivitySummaryDownload.test.ts, app/static/tests/unit/components/sensitivity/sensitivityTab.test.ts, app/static/tests/unit/excel/wodinSensitivitySummaryDownload.test.ts, app/static/tests/unit/store/sensitivity/actions.test.ts
This branch adds download button to the Multi-sensitivity tab, so summary Excel file can be downloaded after run. 
Key changes:
- The changes to the WodinExcelDownload class were actually pretty minimal. The download method now takes an odin result in order to distinguish between single and multi sensitivity to download, and all varying parameter values are determined from the batch itself.
- more tedious refactoring for code sharing in the components - I've pulled out a `SensitivitySummaryDownload` component which is used by both the Sensitivity and Multi-sensitivity tabs, and it uses the `baseSensitivityMixin` to manage the download for both, 
- I may have gone overboard in the unit testing for these units - some functionality tested in both the mixin and component..
- The Sensitivity …
=> mrc-4519 Download multi-sensitivity summary

app/server/src/controllers/configController.ts, app/static/src/app/components/WodinPlot.vue, app/static/src/app/components/options/NumericInput.vue, app/static/src/app/components/options/RunOptions.vue, app/static/src/app/components/run/RunStochasticPlot.vue, app/static/src/app/directives/tooltip.ts, app/static/src/app/plot.ts, app/static/tests/e2e/stochastic.etest.ts, app/static/tests/unit/components/options/numericInput.test.ts, app/static/tests/unit/components/options/runOptions.test.ts, app/static/tests/unit/components/run/runStochasticPlot.test.ts, app/static/tests/unit/components/wodinPlot.test.ts, app/static/tests/unit/directives/tooltip.test.ts, app/static/tests/unit/plot.test.ts
This is finishing off the putting max number of replicates bounds PR #135. You can now enter an array into max allowed which will trigger specified tooltip messages based on what bounds you enter. For example putting below example into `max-allowed` prop will:
```typescript
[
{number: 2, content: "number is good!", variant: "success"},
{number: 4, content: "a little high for me", variant: "warning"},
{number: 6, content: "too high", variant: "error"}
]
```
for a value, x, spawn a success tooltip with message "number is good!" for 2 < x <= 4, warning tooltip for 4 < x <=6 and error tooltip for x > 6. It does not change the emitted value unless x > 6 in which case it will just emit 6 like before.
=> mrc-3710redo Enforced max number of replicates

app/static/src/app/serialise.ts, app/static/src/app/store/multiSensitivity/actions.ts, app/static/src/app/store/sensitivity/actions.ts, app/static/src/app/store/sessions/actions.ts, app/static/src/app/types/serialisationTypes.ts, app/static/tests/e2e/download.etest.ts, app/static/tests/e2e/multiSensitivity.etest.ts, app/static/tests/e2e/sessions.etest.ts, app/static/tests/e2e/utils.ts, app/static/tests/unit/serialiser.test.ts, app/static/tests/unit/store/multiSensitivity/actions.test.ts, app/static/tests/unit/store/sensitivity/actions.test.ts, app/static/tests/unit/store/sessions/actions.test.ts
This branch serialises multiSensitivity state on session save, and runs multiSensitivity on rehydrate if appropriate. 
To test, you should be able to reload a session where multisensitivity options had been modified, and multiSensitivity had been run, and should see the options changes have been preserved. You should also see that the 'produced X solutions' message is visible on the Multi-sensitivity tab, with download button enabled.
=> mrc-4563 Serialise and rehydrate Multi-sensitivity

app/static/package.json, app/static/playwright.config.ts
The Playwright tests have become flaky around selecting options from drop-downs (it seemed to time out when trying to do the select). I tried various diagnostics, checking that the option was really there before attempting to select it etc, and nothing seemed to make a difference except for pinning Playwright back to the previous version (1.37). There's no indication in the docs that the API around selecting options should no longer support the way we ae using it, though it look like they did add some additional options fairly recently (v1.29), so I guess this may be a related bug. 
https://playwright.dev/docs/release-notes
I've added a ticket to unpin later: https://mrc-ide.myjetbrains.com/youtrack/issue/mrc-4623
=> mrc-4621 Pin Playwright version

app/static/package.json, app/static/src/app/components/options/OptionsTab.vue, app/static/tests/unit/components/options/optionsTab.test.ts
Hide graph settings when Multi-sensitivity tab is open, since there is no plotting for Multi-sensitivity
=> mrc-4602 Do not show Graph Settings when Multi-sensitivity tab is open

app/static/package-lock.json, app/static/src/app/components/header/AppHeader.vue, app/static/src/app/components/sessions/SessionsPage.vue, app/static/src/app/serialise.ts, app/static/src/app/store/appState/actions.ts, app/static/src/app/store/appState/mutations.ts, app/static/src/app/store/appState/state.ts, app/static/src/app/store/basic/basic.ts, app/static/src/app/store/fit/fit.ts, app/static/src/app/store/stochastic/stochastic.ts, app/static/src/scss/style.scss, app/static/tests/e2e/sessions.etest.ts, app/static/tests/mocks.ts, app/static/tests/unit/components/sessions/sessionsPage.test.ts, app/static/tests/unit/components/versions/appHeader.test.ts, app/static/tests/unit/serialiser.test.ts, app/static/tests/unit/store/appState/actions.test.ts, app/static/tests/unit/store/appState/mutations.test.ts
Following user feedback on the short course, this branch removes the current session from the main table on the Sessions page, and adds controls related to the current session above the table. If there is no current session the user is given the option to start a new session. 
The controls for copying code and copying link have also been added above the table, There is no longer an option on this page to edit the label for the current session, but the user can do that from the Sessions menu - does that seem sufficient?
Page when there is a current session:
And when there isn't one...
=> mrc-4608 Remove current session from Sessions table

app/static/.eslintrc.js, app/static/src/app/components/options/EditParamSettings.vue, app/static/src/app/components/options/SensitivityOptions.vue, app/static/tests/e2e/multiSensitivity.etest.ts, app/static/tests/unit/components/options/editParamSettings.test.ts, app/static/tests/unit/components/options/sensitivityOptions.test.ts
This branch should ensure that users cannot add parameter settings for the same parameter twice - the Edit Parameter Settings dialog now only provide parameter names in the drop-down for params which are not used in any other current settings in multiSensitivity. 
If only one param is available, that will be shown as text rather than a select.
This does mean that it would not be possible to swap sensitivity settings for two parameter names as you'd need to go through a stage where you had two settings with the same name - but I think it's unlikely anyone would want to do that!
=> mrc-4562 Filter multi-sensitivity parameter settings options to those which are available 

app/server/package-lock.json, app/server/package.json, app/server/src/controllers/sessionsController.ts, app/server/src/db/sessionStore.ts, app/server/tests/controllers/sessionsController.test.ts, app/server/tests/db/sessionStore.test.ts, app/server/tests/integration/session.test.ts, app/static/package-lock.json, app/static/src/app/components/sessions/SessionsPage.vue, app/static/src/app/localStorageManager.ts, app/static/src/app/store/appState/actions.ts, app/static/src/app/store/appState/state.ts, app/static/src/app/store/sessions/actions.ts, app/static/tests/e2e/sessions.etest.ts, app/static/tests/mocks.ts, app/static/tests/unit/components/sessions/sessionsPage.test.ts, app/static/tests/unit/localStorageManager.test.ts, app/static/tests/unit/serialiser.test.ts, app/static/tests/unit/store/appState/actions.test.ts, app/static/tests/unit/store/sessions/actions.test.ts
This branch gives the user a checkbox to filter out duplicate sessions from the Sessions page (checked by default). Unlabelled sessions which are duplicates of a later session will not be shown. Labelled sessions are always shown (I think users would be confused if their labelled session vanished because a later session happened to be identical). 
Now that we're saving hashes for sessions in order to identify duplicates, we could potentially make a further change to only save the data for a hash  once, rather than for every session separately. One for another ticket: https://mrc-ide.myjetbrains.com/youtrack/issue/mrc-4677
=> mrc-4628 Filter out duplicate sessions from Sessions page

app/static/src/app/components/fit/FitTab.vue, app/static/src/app/serialise.ts, app/static/src/app/store/appState/mutations.ts, app/static/src/app/store/modelFit/actions.ts, app/static/src/app/store/modelFit/modelFit.ts, app/static/src/app/store/modelFit/mutations.ts, app/static/src/app/store/modelFit/state.ts, app/static/src/app/types/serialisationTypes.ts, app/static/src/app/userMessages.ts, app/static/tests/e2e/fit.etest.ts, app/static/tests/mocks.ts, app/static/tests/unit/components/fit/fitTab.test.ts, app/static/tests/unit/serialiser.test.ts, app/static/tests/unit/store/modelFit/actions.test.ts, app/static/tests/unit/store/modelFit/mutations.test.ts
This branch ensures that any error throws when a model fit starts running is saved to the state and displayed on the Fit tab. 
An ErrorInfo component has been added to the tab, and if an error is present any previous fit results are faded, with a message shown in the "Action Required" space. 
Steps to generate this error:
- go to Fit app in Wodin
- upload sample data ([influenza_data(1).csv](https://github.com/mrc-ide/wodin/files/13265172/influenza_data.1.csv)), go to options tab and fit tabs
- link "E"
- select "D" and "L" model parameters
- Fit model
- Change tolerance to 7 x 10^ -1
- Fit model
There is another potential error which we should also display, in the modelFit result - this could arise if the modelFit gets further than it does in this case, where an error is thrown in the …
=> mrc-4588 Display model fit error details

app/static/src/app/components/graphConfig/GraphConfig.vue, app/static/src/app/store/graphs/mutations.ts, app/static/tests/e2e/code.etest.ts, app/static/tests/unit/components/graphConfig/graphConfig.test.ts, app/static/tests/unit/store/graphs/mutations.test.ts
User can delete graph from trash icon button in Graphs panel, except if there is only one graph left.
=> mrc-5441 Delete graph

app/static/src/app/components/WodinPlot.vue, app/static/tests/e2e/fit.etest.ts, app/static/tests/e2e/run.etest.ts, app/static/tests/unit/components/wodinPlot.test.ts
Just a one liner really, plus tests! When there are multiple graph configs, show Time label only on final graph (and on fit plot).
=> mrc-5551 Show Time label on final graph only

app/static/src/app/components/mixins/selectVariables.ts, app/static/src/app/components/run/RunPlot.vue, app/static/src/app/components/run/RunTab.vue, app/static/src/app/components/sensitivity/SensitivityTracesPlot.vue, app/static/src/app/plot.ts, app/static/tests/e2e/fit.etest.ts, app/static/tests/e2e/sensitivity.etest.ts, app/static/tests/e2e/utils.ts, app/static/tests/unit/components/graphConfig/graphConfig.test.ts, app/static/tests/unit/components/run/runPlot.test.ts, app/static/tests/unit/components/run/runTab.test.ts, app/static/tests/unit/plot.test.ts
When fit data is linked to a variable, we only render the data points on a graph if the variable is selected on that graph. If the data is unlinked, we display it on all graphs. 
Also, only show 'Sum of squares' value once, after all graphs - could have put it after the relevant graph(s) only (with the linked value selected), but this seems more straightforward.
Also includes an opportunistic bug fix in `onDrop` in `selectVariables` - if a linked variable was dragged from one graph to another, it was being unlinked because we only allow selected variables (ie selected in at least one graph) to be linked. Previously we were removing the dragged variable from the first graph before adding it to the second, triggering its unlinking. Now we add before remove to avoid this. 
I also learned …
=> mrc-5545 Do not show linked variables on graphs which are not showing those variables

app/static/src/app/components/graphConfig/GraphConfig.vue, app/static/src/app/components/mixins/selectVariables.ts, app/static/tests/e2e/code.etest.ts, app/static/tests/unit/components/graphConfig/graphConfig.test.ts, app/static/tests/unit/components/graphConfig/hiddenVariables.test.ts
If user presses Ctrl (or ⌘) key when dragging variabe to another graph, this makes a copy so graph is retained in the source as well as being added to target.
Dragging to or from Hidden variables ignore Ctrl key. 
Now that we can have variables on multiple graphs, this also means that we have to make good on the text "Drag variables here to hide them on *all* graphs" on Hidden variables, so we search all graph configs for variable to hide rather than just removing from source. 
It's not very clear to me why, but I found I now had to specify start and end positions in the e2e drag variable tests. Perhaps something to do with the text change in the drop area meaning the text wraps and height is increased in the default page size? Very odd!
=> mrc-5443 Copy variable on drag if Ctrl key is pressed

app/static/tests/unit/components/basic/basicApp.test.ts, app/static/tests/unit/components/code/codeEditor.test.ts, app/static/tests/unit/components/code/codeTab.test.ts, app/static/tests/unit/components/data/dataTab.test.ts, app/static/tests/unit/components/fit/fitApp.test.ts, app/static/tests/unit/components/fit/fitPlot.test.ts, app/static/tests/unit/components/fit/fitTab.test.ts, app/static/tests/unit/components/fit/support.test.ts, app/static/tests/unit/components/graphConfig/graphConfig.test.ts, app/static/tests/unit/components/graphConfig/graphConfigs.test.ts, app/static/tests/unit/components/graphConfig/graphConfigsCollapsible.test.ts, app/static/tests/unit/components/graphConfig/hiddenVariables.test.ts
part 1 for the vitest upgrade, some main changes to be aware of that youll be seeing in the following PRs:
* `vi.mock` is very similar to `jest.mock` but you do have to mock everything the component uses explicitly so if you import `update` function from `plotly.js-basic-min` then you have to explicitly state it as undefined even if you dont use it in the test so `update: undefined`
* if you want to use mocked functions in `vi.mock` and use them later in your file to see how many times theyve been called for example then you must use `vi.hoisted` to create your mocked functions and these will be available in `vi.mock` and the rest of your tests
* `done` callbacks have been deprecated for a while, so replacing `setTimeout` with await/async
=> Mrc-5952 vitest pt 1

app/static/tests/unit/components/help/draggableDialog.test.ts, app/static/tests/unit/components/help/genericHelp.test.ts, app/static/tests/unit/components/help/helpTab.test.ts, app/static/tests/unit/components/help/markdownPanel.test.ts, app/static/tests/unit/components/mixins/baseSensitivity.test.ts, app/static/tests/unit/components/mixins/includeConfiguredTabs.test.ts, app/static/tests/unit/components/multiSensitivity/multiSensitivityTab.test.ts, app/static/tests/unit/components/run/runPlot.test.ts, app/static/tests/unit/components/run/runStochasticPlot.test.ts, app/static/tests/unit/components/run/runTab.test.ts, app/static/tests/unit/components/run/support.test.ts
i dont think this one has anything super different from the old one, just more of those systematic changes, making sure types and function signatures match!
=> mrc-5953 vitest pt 2

app/static/tests/unit/components/options/advancedSettings.test.ts, app/static/tests/unit/components/options/editParamSettings.test.ts, app/static/tests/unit/components/options/linkData.test.ts, app/static/tests/unit/components/options/numericInput.test.ts, app/static/tests/unit/components/options/optimisationOptions.test.ts, app/static/tests/unit/components/options/optionsTab.test.ts, app/static/tests/unit/components/options/parameterSetView.test.ts, app/static/tests/unit/components/options/parameterSets.test.ts, app/static/tests/unit/components/options/parameterValues.test.ts, app/static/tests/unit/components/options/runOptions.test.ts, app/static/tests/unit/components/options/sensitivityOptions.test.ts, app/static/tests/unit/components/options/sensitivityParamValues.test.ts, app/static/tests/unit/components/options/sensitivityPlotOptions.test.ts, app/static/tests/unit/components/options/standardFormInput.test.ts, app/static/tests/unit/components/options/tagInput.test.ts, app/static/tests/unit/components/stochastic/stochasticApp.test.ts
just making sure types are okay here and same type of changes!
=> Mrc 5954 vitest pt 3

app/static/tests/unit/components/sensitivity/sensitivitySummaryDownload.test.ts, app/static/tests/unit/components/sensitivity/sensitivitySummaryPlot.test.ts, app/static/tests/unit/components/sensitivity/sensitivityTab.test.ts, app/static/tests/unit/components/sensitivity/sensitivityTracesPlot.test.ts, app/static/tests/unit/components/sensitivity/support.test.ts, app/static/tests/unit/components/sessions/editSessionLabel.test.ts, app/static/tests/unit/components/sessions/sessionsPage.test.ts, app/static/tests/unit/components/versions/appHeader.test.ts, app/static/tests/unit/components/versions/versionMenu.test.ts
same stuff here but `getMockResult` was introduced because redraw watches now also watch the result so need that in the test!
=> mrc-5955 vitest pt 4

app/static/tests/mocks.ts, app/static/tests/testUtils.ts, app/static/tests/unit/apiService.test.ts, app/static/tests/unit/csvUpload.test.ts, app/static/tests/unit/directives/help.test.ts, app/static/tests/unit/directives/tooltip.test.ts, app/static/tests/unit/excel/mocks.ts, app/static/tests/unit/excel/wodinModelOutputDownload.test.ts, app/static/tests/unit/excel/wodinSensitivitySummaryDownload.test.ts, app/static/tests/unit/localStorageManager.test.ts, app/static/tests/unit/palette.test.ts, app/static/tests/unit/plot.test.ts, app/static/tests/unit/router.test.ts, app/static/tests/unit/serialiser.test.ts, app/static/tests/unit/utils.test.ts
nothing interesting here, all the same stuff and removing done callbacks
=> mrc-5957 vitest pt 6

app/static/tests/unit/store/appState/actions.test.ts, app/static/tests/unit/store/appState/getters.test.ts, app/static/tests/unit/store/appState/mutations.test.ts, app/static/tests/unit/store/baseSensitivity/actions.test.ts, app/static/tests/unit/store/basic/basic.test.ts, app/static/tests/unit/store/multiSensitivity/actions.test.ts, app/static/tests/unit/store/multiSensitivity/getters.test.ts, app/static/tests/unit/store/multiSensitivity/mutations.test.ts, app/static/tests/unit/store/sensitivity/actions.test.ts, app/static/tests/unit/store/sensitivity/getters.test.ts, app/static/tests/unit/store/sensitivity/mutations.test.ts
i have created a `baseSensitivity` test file that only tests those, this used to live in the `senstivity` test file which was causing it to run twice for some reason and the test was very flaky, but now the test only runs once and it is probably better if it has its own file anyway
=> mrc-5958 vitest pt 7

app/server/views/app.mustache
Deploy to epimodels with latest wodin main image is resulting in apps not rendering, because they are trying to fetch wodin.js and wodin.css from "/" rather than relative to baseUrl.  This branch fixes this issue and is deployed to wodin-dev e.g. https://wodin-dev.dide.ic.ac.uk/msc-idm-2022/apps/heterogeneity-1
There's another issue, which is that a lot of the site index.html files are trying to use bootstrap.css from their site base url, which is not being found, resulting in unstyled pages e.g. https://wodin-dev.dide.ic.ac.uk/msc-idm-2022/ . I forget what we'd agreed to do there - did we say that sites ought to just use bootstrap themselves? Given that we'd like to redeploy this soon for the Royal Society app, and that we never got round to updating all the sites individually, we could …
=> mrc-6151 get script and css from base url

app/static/src/components/run/RunStochasticPlot.vue, app/static/src/components/run/RunTab.vue, app/static/src/components/sensitivity/SensitivityTab.vue, app/static/tests/unit/components/run/runStochasticPlot.test.ts, app/static/tests/unit/components/run/runTab.test.ts, app/static/tests/unit/components/sensitivity/sensitivityTab.test.ts, config-static/index.html
I am on the fence about testing this:
This doesn't add any new features to wodin, wodin has graph controls on the side where you can select or deselect variables. This is just another way to achieve that filtering. Also this PR is temporary and once the d3 graph stuff is made into a package, we should rip this out (guess ill make a ticket for it?)
So personally, i dont think its worth testing this, itll just be extra stuff to remove later
I also think after this PR, we can start incorporating this into OJs word document as we have most of the necessary features and i would like to start properly packaging up the d3 stuff so we can stop making small ephemeral changes to wodin
I did find a bug, stochastic plot needs a redraw watch on the selected parameters, currently changing selected …
=> Mrc 6357 - Ability to filter traces on a graph
